# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
        environment:
          RDS_DB_NAME: circle_test
          RDS_USERNAME: postgres
          RDS_PASSWORD: ''
          RDS_HOSTNAME: localhost
          RDS_PORT: 5432
      - image: cimg/postgres:14.6
    steps:
      - checkout
      - run:
          name: Install Environment
          command: pip install -r requirements.txt
      - run:
          name: Lint
          command: flake8
      - run:
          name: Test
          command: python manage.py test

workflows:
  test-code:
    jobs:
      - build-and-test
      - eb/deploy:
          context: aws-creds
          environment-name: dogsitter-dev
          application-name: dogsitter
          filters:
            branches:
              only:
                - master
          requires:
            - build-and-test
