# Generated by Django 4.0.6 on 2022-07-13 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0003_remove_dog_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 18, 19, 18, 19511)),
        ),
    ]
