# Generated by Django 4.0.6 on 2022-07-13 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0004_dog_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 7, 13, 18, 22, 5, 614716)),
        ),
    ]
