# Generated by Django 4.0.6 on 2022-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0007_alter_dog_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='good_with_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_cats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='good_with_kids',
            field=models.BooleanField(default=False),
        ),
    ]
