# Generated by Django 4.0.6 on 2022-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0008_dog_good_with_dogs_alter_dog_good_with_cats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
