# Generated by Django 4.0.6 on 2022-07-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0011_remove_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Bulldog', max_length=100),
        ),
    ]
