# Generated by Django 4.0.6 on 2022-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0012_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('boxer', 'Boxer'), ('golden', 'Golden'), ('bulldog', 'Bulldog')], default='', max_length=100),
        ),
    ]
