# Generated by Django 4.0.6 on 2022-07-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0014_merge_20220718_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimages',
            name='images',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
