# Generated by Django 4.0.6 on 2022-07-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0015_multipleimages_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleimages',
            old_name='images',
            new_name='image',
        ),
    ]
