# Generated by Django 4.0.6 on 2022-07-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0018_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dog_pics'),
        ),
    ]
