# Generated by Django 4.0.6 on 2022-07-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0022_doggalleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogGalleryImage',
        ),
    ]
