# Generated by Django 4.0.6 on 2022-07-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0023_delete_doggalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_pics')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsitter_core.dog')),
            ],
        ),
    ]
