# Generated by Django 4.0.6 on 2022-08-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0024_doggalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='dog-default.jpg', upload_to='dog_pics'),
        ),
    ]
