# Generated by Django 4.0.6 on 2022-08-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0027_alter_dog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='housing',
            field=models.CharField(choices=[('alone', 'I live alone'), ('spouse', 'I live with my spouse/partner'), ('roommates', 'I live with roommates'), ('spouse and children', 'I live with my spouse and children'), ('children', 'I live with children')], default='', max_length=100),
        ),
    ]
