# Generated by Django 4.0.6 on 2022-08-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0028_profile_housing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='housing',
            field=models.CharField(choices=[('I live alone', 'alone'), ('I live with my spouse/partner', 'spouse/partner'), ('I live with roommates', 'roommates'), ('I live with my spouse and children', 'spouse/children'), ('I live with children', 'children')], default='', max_length=100),
        ),
    ]
