# Generated by Django 4.0.6 on 2022-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0029_alter_profile_housing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='housing',
            field=models.CharField(choices=[('I live alone', 'I live alone'), ('I live with my spouse/partner', 'I live with my spouse/partner'), ('I live with roommates', 'I live with roommates'), ('I live with my spouse and children', 'I live with my spouse and children'), ('I live with children', 'I live with children')], default='', max_length=100),
        ),
    ]
