# Generated by Django 4.0.6 on 2022-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0031_profile_living_arrangements_alter_profile_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yard',
            field=models.BooleanField(default=False),
        ),
    ]
