# Generated by Django 4.0.6 on 2022-08-09 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogsitter_core', '0032_profile_yard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='living_arrangements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yard',
        ),
        migrations.CreateModel(
            name='DogSitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_arrangements', models.CharField(choices=[('I live alone', 'I live alone'), ('I live with my spouse/partner', 'I live with my spouse/partner'), ('I live with roommates', 'I live with roommates'), ('I live with my spouse and children', 'I live with my spouse and children'), ('I live with children', 'I live with children')], default='', max_length=100)),
                ('housing', models.CharField(choices=[('I live in a house', 'I live in a house'), ('I live in an apartment', 'I live in an apartment'), ('I live in a condo', 'I live in a condo'), ('I live in an alternative style of housing', 'I live in an alternative style of housing')], default='', max_length=100)),
                ('yard', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
