# Generated by Django 4.0.6 on 2022-08-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogsitter_core', '0033_remove_profile_cost_remove_profile_housing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
