# Generated by Django 4.0.6 on 2022-08-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0039_alter_dogsitterprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitterprofile',
            name='dog_sizes',
            field=models.CharField(choices=[('Small Dogs (up to 22lbs)', 'Small Dogs (up to 22lbs)'), ('Medium Dogs (23lbs to 55lbs)', 'Medium Dogs (23lbs to 55lbs)'), ('Large Dogs (up to 100lbs)', 'Large Dogs (up to 100lbs)'), ('Extra Large Dogs (over 100lbs)', 'Extra Large Dogs (over 100lbs)')], default='', max_length=100),
        ),
    ]
