# Generated by Django 4.0.6 on 2022-08-10 17:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0040_dogsitterprofile_dog_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitterprofile',
            name='hours_alone',
            field=models.CharField(choices=[('Your dog will not be left alone', 'Your dog will not be left alone'), ('Up to two hours', 'Up to two hours'), ('Up to four hours', 'Up to four hours'), ('Up to eight hours', 'Up to eight hours')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='dog_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Small Dogs (up to 22lbs)', 'Small Dogs (up to 22lbs)'), ('Medium Dogs (23lbs to 55lbs)', 'Medium Dogs (23lbs to 55lbs)'), ('Large Dogs (up to 100lbs)', 'Large Dogs (up to 100lbs)'), ('Extra Large Dogs (over 100lbs)', 'Extra Large Dogs (over 100lbs)')], default='', max_length=110),
        ),
    ]
