# Generated by Django 4.0.6 on 2022-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0041_dogsitterprofile_hours_alone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitterprofile',
            name='sleeping_arrangements',
            field=models.CharField(choices=[('dogbed', 'on a dogbed'), ('on the bed', 'on the bed'), ('on the couch', 'on the couch'), ('wherever they would like', 'wherever they would like')], default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='dogsitterprofile',
            name='walks',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('more than two', 'more than two')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='hours_alone',
            field=models.CharField(choices=[('Your dog will not be left alone', 'Your dog will not be left alone'), ('Up to two hours', 'Up to two hours'), ('Up to four hours', 'Up to four hours'), ('Up to eight hours', 'Up to eight hours')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='housing',
            field=models.CharField(choices=[('I live in a house', 'I live in a house'), ('I live in an apartment', 'I live in an apartment'), ('I live in a condo', 'I live in a condo'), ('I live in an alternative style of housing', 'I live in an alternative style of housing')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='living_arrangements',
            field=models.CharField(choices=[('I live alone', 'I live alone'), ('I live with my spouse/partner', 'I live with my spouse/partner'), ('I live with roommates', 'I live with roommates'), ('I live with my spouse and children', 'I live with my spouse and children'), ('I live with children', 'I live with children')], default='', max_length=1000),
        ),
    ]
