# Generated by Django 4.0.6 on 2022-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0042_dogsitterprofile_sleeping_arrangements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='hours_alone',
            field=models.CharField(choices=[('your dog will not be left alone', 'Your dog will not be left alone'), ('up to two hours', 'Up to two hours'), ('up to four hours', 'Up to four hours'), ('up to eight hours', 'Up to eight hours')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='sleeping_arrangements',
            field=models.CharField(choices=[('dogbed', 'On a dogbed'), ('on the bed', 'On the bed'), ('on the couch', 'On the couch'), ('wherever they would like', 'Wherever they would like')], default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dogsitterprofile',
            name='walks',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('more than two', 'More than two')], default='', max_length=1000),
        ),
    ]
