# Generated by Django 4.0.6 on 2022-12-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogsitter_core', '0028_alter_dog_breed'),
        ('dogsitter_core', '0044_remove_profile_is_dog_sitter'),
    ]

    operations = [
    ]
